//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.07.18 at 10:24:00 AM EEST 
//


package com.rosteach.xml.ordersp;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.rosteach.xml.ordersp package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _ORDRSPHEADRECIPIENT_QNAME = new QName("", "RECIPIENT");
    private final static QName _ORDRSPHEADEDIINTERCHANGEID_QNAME = new QName("", "EDIINTERCHANGEID");
    private final static QName _ORDRSPHEADPOSITION_QNAME = new QName("", "POSITION");
    private final static QName _ORDRSPHEADINVOICEPARTNER_QNAME = new QName("", "INVOICEPARTNER");
    private final static QName _ORDRSPHEADSENDER_QNAME = new QName("", "SENDER");
    private final static QName _ORDRSPHEADBUYER_QNAME = new QName("", "BUYER");
    private final static QName _ORDRSPHEADSUPPLIER_QNAME = new QName("", "SUPPLIER");
    private final static QName _ORDRSPHEADDELIVERYPLACE_QNAME = new QName("", "DELIVERYPLACE");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.rosteach.xml.ordersp
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ORDRSP }
     * 
     */
    public ORDRSP createORDRSP() {
        return new ORDRSP();
    }

    /**
     * Create an instance of {@link ORDRSP.HEAD }
     * 
     */
    public ORDRSP.HEAD createORDRSPHEAD() {
        return new ORDRSP.HEAD();
    }

    /**
     * Create an instance of {@link ORDRSP.HEAD.POSITION }
     * 
     */
    public ORDRSP.HEAD.POSITION createORDRSPHEADPOSITION() {
        return new ORDRSP.HEAD.POSITION();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Long }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "RECIPIENT", scope = ORDRSP.HEAD.class)
    public JAXBElement<Long> createORDRSPHEADRECIPIENT(Long value) {
        return new JAXBElement<Long>(_ORDRSPHEADRECIPIENT_QNAME, Long.class, ORDRSP.HEAD.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Short }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "EDIINTERCHANGEID", scope = ORDRSP.HEAD.class)
    public JAXBElement<Short> createORDRSPHEADEDIINTERCHANGEID(Short value) {
        return new JAXBElement<Short>(_ORDRSPHEADEDIINTERCHANGEID_QNAME, Short.class, ORDRSP.HEAD.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ORDRSP.HEAD.POSITION }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "POSITION", scope = ORDRSP.HEAD.class)
    public JAXBElement<ORDRSP.HEAD.POSITION> createORDRSPHEADPOSITION(ORDRSP.HEAD.POSITION value) {
        return new JAXBElement<ORDRSP.HEAD.POSITION>(_ORDRSPHEADPOSITION_QNAME, ORDRSP.HEAD.POSITION.class, ORDRSP.HEAD.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Long }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "INVOICEPARTNER", scope = ORDRSP.HEAD.class)
    public JAXBElement<Long> createORDRSPHEADINVOICEPARTNER(Long value) {
        return new JAXBElement<Long>(_ORDRSPHEADINVOICEPARTNER_QNAME, Long.class, ORDRSP.HEAD.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Long }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "SENDER", scope = ORDRSP.HEAD.class)
    public JAXBElement<Long> createORDRSPHEADSENDER(Long value) {
        return new JAXBElement<Long>(_ORDRSPHEADSENDER_QNAME, Long.class, ORDRSP.HEAD.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "BUYER", scope = ORDRSP.HEAD.class)
    public JAXBElement<String> createORDRSPHEADBUYER(String value) {
        return new JAXBElement<String>(_ORDRSPHEADBUYER_QNAME, String.class, ORDRSP.HEAD.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Long }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "SUPPLIER", scope = ORDRSP.HEAD.class)
    public JAXBElement<Long> createORDRSPHEADSUPPLIER(Long value) {
        return new JAXBElement<Long>(_ORDRSPHEADSUPPLIER_QNAME, Long.class, ORDRSP.HEAD.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Long }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "DELIVERYPLACE", scope = ORDRSP.HEAD.class)
    public JAXBElement<Long> createORDRSPHEADDELIVERYPLACE(Long value) {
        return new JAXBElement<Long>(_ORDRSPHEADDELIVERYPLACE_QNAME, Long.class, ORDRSP.HEAD.class, value);
    }

}
