//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.07.18 at 10:24:00 AM EEST 
//


package com.rosteach.xml.ordersp;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlElementRefs;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;

import com.rosteach.xml.lktrans.ORDER;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="NUMBER" type="{http://www.w3.org/2001/XMLSchema}short"/>
 *         &lt;element name="DATE" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="TIME" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ORDERNUMBER" type="{http://www.w3.org/2001/XMLSchema}short"/>
 *         &lt;element name="ORDERDATE" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="DELIVERYDATE" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="DELIVERYTIME" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ACTION" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *         &lt;element name="CAMPAIGNNUMBER" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *         &lt;element name="HEAD">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;choice maxOccurs="unbounded" minOccurs="0">
 *                   &lt;element name="BUYER" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="SUPPLIER" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *                   &lt;element name="DELIVERYPLACE" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *                   &lt;element name="INVOICEPARTNER" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *                   &lt;element name="SENDER" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *                   &lt;element name="RECIPIENT" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *                   &lt;element name="EDIINTERCHANGEID" type="{http://www.w3.org/2001/XMLSchema}short"/>
 *                   &lt;element name="POSITION">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="POSITIONNUMBER" type="{http://www.w3.org/2001/XMLSchema}short"/>
 *                             &lt;element name="PRODUCT" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *                             &lt;element name="PRODUCTIDBUYER" type="{http://www.w3.org/2001/XMLSchema}short"/>
 *                             &lt;element name="DESCRIPTION" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="PRICE" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *                             &lt;element name="VAT" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *                             &lt;element name="PRODUCTTYPE" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *                             &lt;element name="ORDEREDQUANTITY" type="{http://www.w3.org/2001/XMLSchema}short"/>
 *                             &lt;element name="ACCEPTEDQUANTITY" type="{http://www.w3.org/2001/XMLSchema}short"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/choice>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "number",
    "date",
    "time",
    "ordernumber",
    "orderdate",
    "deliverydate",
    "deliverytime",
    "action",
    "campaignnumber",
    "head"
})
@XmlRootElement(name = "ORDRSP")
public class ORDRSP {

    @XmlElement(name = "NUMBER")
    protected long number;
    @XmlElement(name = "DATE", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar date;
    @XmlElement(name = "TIME", required = true)
    protected String time;
    @XmlElement(name = "ORDERNUMBER")
    protected String ordernumber;
    @XmlElement(name = "ORDERDATE", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar orderdate;
    @XmlElement(name = "DELIVERYDATE", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar deliverydate;
    @XmlElement(name = "DELIVERYTIME", required = true)
    protected String deliverytime;
    @XmlElement(name = "ACTION")
    protected byte action;
    @XmlElement(name = "CAMPAIGNNUMBER")
    protected String campaignnumber;
    @XmlElement(name = "HEAD", required = true)
    protected ORDRSP.HEAD head;

    /**
     * Gets the value of the number property.
     * 
     */
    public long getNUMBER() {
        return number;
    }

    /**
     * Sets the value of the number property.
     * 
     */
    public void setNUMBER(long l) {
        this.number = l;
    }

    /**
     * Gets the value of the date property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDATE() {
        return date;
    }

    /**
     * Sets the value of the date property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDATE(XMLGregorianCalendar value) {
        this.date = value;
    }

    /**
     * Gets the value of the time property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTIME() {
        return time;
    }

    /**
     * Sets the value of the time property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTIME(String value) {
        this.time = value;
    }

    /**
     * Gets the value of the ordernumber property.
     * 
     */
    public String getORDERNUMBER() {
        return ordernumber;
    }

    /**
     * Sets the value of the ordernumber property.
     * 
     */
    public void setORDERNUMBER(String value) {
        this.ordernumber = value;
    }

    /**
     * Gets the value of the orderdate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getORDERDATE() {
        return orderdate;
    }

    /**
     * Sets the value of the orderdate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setORDERDATE(XMLGregorianCalendar value) {
        this.orderdate = value;
    }

    /**
     * Gets the value of the deliverydate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDELIVERYDATE() {
        return deliverydate;
    }

    /**
     * Sets the value of the deliverydate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDELIVERYDATE(XMLGregorianCalendar value) {
        this.deliverydate = value;
    }

    /**
     * Gets the value of the deliverytime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDELIVERYTIME() {
        return deliverytime;
    }

    /**
     * Sets the value of the deliverytime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDELIVERYTIME(String value) {
        this.deliverytime = value;
    }

    /**
     * Gets the value of the action property.
     * 
     */
    public byte getACTION() {
        return action;
    }

    /**
     * Sets the value of the action property.
     * 
     */
    public void setACTION(byte value) {
        this.action = value;
    }

    /**
     * Gets the value of the campaignnumber property.
     * 
     */
    public String getCAMPAIGNNUMBER() {
        return campaignnumber;
    }

    /**
     * Sets the value of the campaignnumber property.
     * 
     */
    public void setCAMPAIGNNUMBER(String campaignNumber2) {
        this.campaignnumber = campaignNumber2;
    }

    /**
     * Gets the value of the head property.
     * 
     * @return
     *     possible object is
     *     {@link ORDRSP.HEAD }
     *     
     */
    public ORDRSP.HEAD getHEAD() {
        return head;
    }

    /**
     * Sets the value of the head property.
     * 
     * @param value
     *     allowed object is
     *     {@link ORDRSP.HEAD }
     *     
     */
    public void setHEAD(ORDRSP.HEAD value) {
        this.head = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;choice maxOccurs="unbounded" minOccurs="0">
     *         &lt;element name="BUYER" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="SUPPLIER" type="{http://www.w3.org/2001/XMLSchema}long"/>
     *         &lt;element name="DELIVERYPLACE" type="{http://www.w3.org/2001/XMLSchema}long"/>
     *         &lt;element name="INVOICEPARTNER" type="{http://www.w3.org/2001/XMLSchema}long"/>
     *         &lt;element name="SENDER" type="{http://www.w3.org/2001/XMLSchema}long"/>
     *         &lt;element name="RECIPIENT" type="{http://www.w3.org/2001/XMLSchema}long"/>
     *         &lt;element name="EDIINTERCHANGEID" type="{http://www.w3.org/2001/XMLSchema}short"/>
     *         &lt;element name="POSITION">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="POSITIONNUMBER" type="{http://www.w3.org/2001/XMLSchema}short"/>
     *                   &lt;element name="PRODUCT" type="{http://www.w3.org/2001/XMLSchema}long"/>
     *                   &lt;element name="PRODUCTIDBUYER" type="{http://www.w3.org/2001/XMLSchema}short"/>
     *                   &lt;element name="DESCRIPTION" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="PRICE" type="{http://www.w3.org/2001/XMLSchema}float"/>
     *                   &lt;element name="VAT" type="{http://www.w3.org/2001/XMLSchema}byte"/>
     *                   &lt;element name="PRODUCTTYPE" type="{http://www.w3.org/2001/XMLSchema}byte"/>
     *                   &lt;element name="ORDEREDQUANTITY" type="{http://www.w3.org/2001/XMLSchema}short"/>
     *                   &lt;element name="ACCEPTEDQUANTITY" type="{http://www.w3.org/2001/XMLSchema}short"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/choice>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "supplier",
        "buyer",
        "deliveryplace",
        "invoicepartner",
        "sender",
        "recipient",
        "ediinterchangeid",
        "position"
    })
    public static class HEAD {
    	
    	 @XmlElement(name = "SUPPLIER")
         protected long supplier;
         @XmlElement(name = "BUYER")
         protected long buyer;
         @XmlElement(name = "DELIVERYPLACE")
         protected long deliveryplace;
         @XmlElement(name = "INVOICEPARTNER")
         protected long invoicepartner;
         @XmlElement(name = "SENDER")
         protected long sender;
         @XmlElement(name = "RECIPIENT")
         protected long recipient;
         @XmlElement(name = "EDIINTERCHANGEID", required = true)
         protected String ediinterchangeid;
         @XmlElement(name = "POSITION")
         protected List<ORDRSP.HEAD.POSITION> position;
    	

         public List<ORDRSP.HEAD.POSITION> getPOSITION() {
             if (position == null) {
                 position = new ArrayList<ORDRSP.HEAD.POSITION>();
             }
             return this.position;
         }

        public long getSupplier() {
			return supplier;
		}





		public void setSupplier(long supplier) {
			this.supplier = supplier;
		}





		public long getBuyer() {
			return buyer;
		}





		public void setBuyer(long buyer) {
			this.buyer = buyer;
		}





		public long getDeliveryplace() {
			return deliveryplace;
		}





		public void setDeliveryplace(long deliveryplace) {
			this.deliveryplace = deliveryplace;
		}





		public long getInvoicepartner() {
			return invoicepartner;
		}





		public void setInvoicepartner(long invoicepartner) {
			this.invoicepartner = invoicepartner;
		}





		public long getSender() {
			return sender;
		}





		public void setSender(long sender) {
			this.sender = sender;
		}





		public long getRecipient() {
			return recipient;
		}





		public void setRecipient(long recipient) {
			this.recipient = recipient;
		}





		public String getEdiinterchangeid() {
			return ediinterchangeid;
		}





		public void setEdiinterchangeid(String ediinterchangeid) {
			this.ediinterchangeid = ediinterchangeid;
		}





		/**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="POSITIONNUMBER" type="{http://www.w3.org/2001/XMLSchema}short"/>
         *         &lt;element name="PRODUCT" type="{http://www.w3.org/2001/XMLSchema}long"/>
         *         &lt;element name="PRODUCTIDBUYER" type="{http://www.w3.org/2001/XMLSchema}short"/>
         *         &lt;element name="DESCRIPTION" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="PRICE" type="{http://www.w3.org/2001/XMLSchema}float"/>
         *         &lt;element name="VAT" type="{http://www.w3.org/2001/XMLSchema}byte"/>
         *         &lt;element name="PRODUCTTYPE" type="{http://www.w3.org/2001/XMLSchema}byte"/>
         *         &lt;element name="ORDEREDQUANTITY" type="{http://www.w3.org/2001/XMLSchema}short"/>
         *         &lt;element name="ACCEPTEDQUANTITY" type="{http://www.w3.org/2001/XMLSchema}short"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "positionnumber",
            "product",
            "productidbuyer",
            "description",
            "price",
            "vat",
            "producttype",
            "orderedquantity",
            "acceptedquantity"
        })
        public static class POSITION {

            @XmlElement(name = "POSITIONNUMBER")
            protected short positionnumber;
            @XmlElement(name = "PRODUCT")
            protected String product;
            @XmlElement(name = "PRODUCTIDBUYER")
            protected String productidbuyer;
            @XmlElement(name = "DESCRIPTION", required = true)
            protected String description;
            @XmlElement(name = "PRICE")
            protected Double price;
            @XmlElement(name = "VAT")
            protected byte vat;
            @XmlElement(name = "PRODUCTTYPE")
            protected int producttype;
            @XmlElement(name = "ORDEREDQUANTITY")
            protected Double orderedquantity;
            @XmlElement(name = "ACCEPTEDQUANTITY")
            protected Double acceptedquantity;

            /**
             * Gets the value of the positionnumber property.
             * 
             */
            public short getPOSITIONNUMBER() {
                return positionnumber;
            }

            /**
             * Sets the value of the positionnumber property.
             * 
             */
            public void setPOSITIONNUMBER(short value) {
                this.positionnumber = value;
            }

            /**
             * Gets the value of the product property.
             * 
             */
            public String getPRODUCT() {
                return product;
            }

            /**
             * Sets the value of the product property.
             * 
             */
            public void setPRODUCT(String value) {
                this.product = value;
            }

            /**
             * Gets the value of the productidbuyer property.
             * 
             */
            public String getPRODUCTIDBUYER() {
                return productidbuyer;
            }

            /**
             * Sets the value of the productidbuyer property.
             * 
             */
            public void setPRODUCTIDBUYER(String string) {
                this.productidbuyer = string;
            }

            /**
             * Gets the value of the description property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getDESCRIPTION() {
                return description;
            }

            /**
             * Sets the value of the description property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setDESCRIPTION(String value) {
                this.description = value;
            }

            /**
             * Gets the value of the price property.
             * 
             */
            public Double getPRICE() {
                return price;
            }

            /**
             * Sets the value of the price property.
             * 
             */
            public void setPRICE(Double double1) {
                this.price = double1;
            }

            /**
             * Gets the value of the vat property.
             * 
             */
            public byte getVAT() {
                return vat;
            }

            /**
             * Sets the value of the vat property.
             * 
             */
            public void setVAT(byte value) {
                this.vat = value;
            }

            /**
             * Gets the value of the producttype property.
             * 
             */
            public int getPRODUCTTYPE() {
                return producttype;
            }

            /**
             * Sets the value of the producttype property.
             * 
             */
            public void setPRODUCTTYPE(int i) {
                this.producttype = i;
            }

            /**
             * Gets the value of the orderedquantity property.
             * 
             */
            public Double getORDEREDQUANTITY() {
                return orderedquantity;
            }

            /**
             * Sets the value of the orderedquantity property.
             * 
             */
            public void setORDEREDQUANTITY(Double double1) {
                this.orderedquantity = double1;
            }

            /**
             * Gets the value of the acceptedquantity property.
             * 
             */
            public Double getACCEPTEDQUANTITY() {
                return acceptedquantity;
            }

            /**
             * Sets the value of the acceptedquantity property.
             * 
             */
            public void setACCEPTEDQUANTITY(Double double1) {
                this.acceptedquantity = double1;
            }

        }

    }

}
