//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.08.08 at 10:12:33 AM EEST 
//


package com.rosteach.entities;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;
import javax.xml.datatype.XMLGregorianCalendar;


@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "header",
    "sides",
    "parameters",
    "table",
    "documenttotal"
})
@XmlRootElement(name = "ЕлектроннийДокумент")
public class COMDOC{

    @XmlElement(name="Заголовок",required = true)
    protected COMDOC.Header header;
    @XmlElement(name="Сторони",required = true)
    protected COMDOC.Sides sides;
    @XmlElement(name="Параметри",required = true)
    protected COMDOC.Parameters parameters;
    @XmlElement(name="Таблиця",required = true)
    protected COMDOC.Table table;
    @XmlElement(name="ВсьогоПоДокументу",required = true)
    protected COMDOC.Documenttotal documenttotal;
    
    public COMDOC(){
    	
    }
    
    public COMDOC(Header header, Sides sides, Parameters parameters, Table table, Documenttotal documenttotal) {
		this.header = header;
		this.sides = sides;
		this.parameters = parameters;
		this.table = table;
		this.documenttotal = documenttotal;
	}

	/**
     * Gets the value of the header property.
     * 
     * @return
     *     possible object is
     *     {@link COMDOC.Header }
     *     
     */
    public COMDOC.Header getHeader() {
        return header;
    }

    /**
     * Sets the value of the header property.
     * 
     * @param value
     *     allowed object is
     *     {@link COMDOC.Header }
     *     
     */
    public void setHeader(COMDOC.Header value) {
        this.header = value;
    }

    /**
     * Gets the value of the sides property.
     * 
     * @return
     *     possible object is
     *     {@link COMDOC.Sides }
     *     
     */
    public COMDOC.Sides getSides() {
        return sides;
    }

    /**
     * Sets the value of the sides property.
     * 
     * @param value
     *     allowed object is
     *     {@link COMDOC.Sides }
     *     
     */
    public void setSides(COMDOC.Sides value) {
        this.sides = value;
    }

    /**
     * Gets the value of the parameters property.
     * 
     * @return
     *     possible object is
     *     {@link COMDOC.Parameters }
     *     
     */
    public COMDOC.Parameters getParameters() {
        return parameters;
    }

    /**
     * Sets the value of the parameters property.
     * 
     * @param value
     *     allowed object is
     *     {@link COMDOC.Parameters }
     *     
     */
    public void setParameters(COMDOC.Parameters value) {
        this.parameters = value;
    }

    /**
     * Gets the value of the table property.
     * 
     * @return
     *     possible object is
     *     {@link COMDOC.Table }
     *     
     */
    public COMDOC.Table getTable() {
        return table;
    }

    /**
     * Sets the value of the table property.
     * 
     * @param value
     *     allowed object is
     *     {@link COMDOC.Table }
     *     
     */
    public void setTable(COMDOC.Table value) {
        this.table = value;
    }

    /**
     * Gets the value of the documenttotal property.
     * 
     * @return
     *     possible object is
     *     {@link COMDOC.Documenttotal }
     *     
     */
    public COMDOC.Documenttotal getDocumenttotal() {
        return documenttotal;
    }

    /**
     * Sets the value of the documenttotal property.
     * 
     * @param value
     *     allowed object is
     *     {@link COMDOC.Documenttotal }
     *     
     */
    public void setDocumenttotal(COMDOC.Documenttotal value) {
        this.documenttotal = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="summwithPDV" type="{http://www.w3.org/2001/XMLSchema}float"/>
     *         &lt;element name="PDV" type="{http://www.w3.org/2001/XMLSchema}float"/>
     *         &lt;element name="summ" type="{http://www.w3.org/2001/XMLSchema}float"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "summwithPDV",
        "pdv",
        "summ"
    })
    public static class Documenttotal {
    	@XmlElement(name = "СумаБезПДВ")
        protected double summwithPDV;
        @XmlElement(name = "ПДВ")
        protected double pdv;
        @XmlElement(name = "Сума")
        protected double summ;
        
        public Documenttotal(){
        	
        }
        public Documenttotal(double summwithPDV, double pdv, double summ) {
			this.summwithPDV = summwithPDV;
			this.pdv = pdv;
			this.summ = summ;
		}


		/**
         * Gets the value of the summwithPDV property.
         * 
         */
        public double getSummwithPDV() {
            return summwithPDV;
        }

        /**
         * Sets the value of the summwithPDV property.
         * 
         */
        public void setSummwithPDV(double value) {
            this.summwithPDV = value;
        }

        /**
         * Gets the value of the pdv property.
         * 
         */
        public double getPDV() {
            return pdv;
        }

        /**
         * Sets the value of the pdv property.
         * 
         */
        public void setPDV(double value) {
            this.pdv = value;
        }

        /**
         * Gets the value of the summ property.
         * 
         */
        public double getSumm() {
            return summ;
        }

        /**
         * Sets the value of the summ property.
         * 
         */
        public void setSumm(double value) {
            this.summ = value;
        }

    }
    
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "number",
        "type",
        "typecode",
        "date",
        "invoicenumber",
        "comment",
        "docreason"
    })
    public static class Header {
    	@XmlElement(name="НомерДокументу",required = true)
        protected String number;
    	@XmlElement(name="ТипДокументу",required = true)
        protected String type;
    	@XmlElement(name="КодТипуДокументу",required = true)
        protected String typecode;
    	@XmlElement(name="ДатаДокументу",required = true)
        protected String date;
    	@XmlElement(name="НомерЗамовлення",required = true)
    	protected String invoicenumber;
        @XmlElement(name="Коментар",required = true)
        protected COMDOC.Header.Comment comment;
        @XmlElement(name="ДокПідстава",required = true)
        protected COMDOC.Header.Docreason docreason;
        
        public Header(){
        	
        }
        public Header(String number, String type, String typecode, String date, String invoicenumber,
				Comment comment, Docreason docreason) {
			this.number = number;
			this.type = type;
			this.typecode = typecode;
			this.date = date;
			this.invoicenumber = invoicenumber;
			this.comment = comment;
			this.docreason = docreason;
		}

		/**
         * Gets the value of the number property.
         * 
         */
        public String getNumber() {
            return number;
        }

        /**
         * Sets the value of the number property.
         * 
         */
        public void setNumber(String value) {
            this.number = value;
        }

        /**
         * Gets the value of the type property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getType() {
            return type;
        }

        /**
         * Sets the value of the type property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setType(String value) {
            this.type = value;
        }

        /**
         * Gets the value of the typecode property.
         * 
         */
        public String getTypecode() {
            return typecode;
        }

        /**
         * Sets the value of the typecode property.
         * 
         */
        public void setTypecode(String value) {
            this.typecode = value;
        }

        /**
         * Gets the value of the date property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public String getDate() {
            return date;
        }

        /**
         * Sets the value of the date property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setDate(String value) {
            this.date = value;
        }

        /**
         * Gets the value of the invoicenumber property.
         * 
         */
        public String getInvoicenumber() {
            return invoicenumber;
        }

        /**
         * Sets the value of the invoicenumber property.
         * 
         */
        public void setInvoicenumber(String value) {
            this.invoicenumber = value;
        }

        /**
         * Gets the value of the comment property.
         * 
         * @return
         *     possible object is
         *     {@link COMDOC.Header.Comment }
         *     
         */
        public COMDOC.Header.Comment getComment() {
            return comment;
        }

        /**
         * Sets the value of the comment property.
         * 
         * @param value
         *     allowed object is
         *     {@link COMDOC.Header.Comment }
         *     
         */
        public void setComment(COMDOC.Header.Comment value) {
            this.comment = value;
        }

        /**
         * Gets the value of the docreason property.
         * 
         * @return
         *     possible object is
         *     {@link COMDOC.Header.Docreason }
         *     
         */
        public COMDOC.Header.Docreason getDocreason() {
            return docreason;
        }

        /**
         * Sets the value of the docreason property.
         * 
         * @param value
         *     allowed object is
         *     {@link COMDOC.Header.Docreason }
         *     
         */
        public void setDocreason(COMDOC.Header.Docreason value) {
            this.docreason = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;simpleContent>
         *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
         *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}byte" />
         *     &lt;/extension>
         *   &lt;/simpleContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "value"
        })
        public static class Comment {

            @XmlValue
            protected String value;
            @XmlAttribute(name = "id")
            protected int id;
            
            public Comment(){
            	
            }
            
            public Comment(String value, int id) {
				this.value = value;
				this.id = id;
			}

			/**
             * Gets the value of the value property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getValue() {
                return value;
            }

            /**
             * Sets the value of the value property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setValue(String value) {
                this.value = value;
            }

            /**
             * Gets the value of the id property.
             * 
             * @return
             *     possible object is
             *     {@link Byte }
             *     
             */
            public int getId() {
                return id;
            }

            /**
             * Sets the value of the id property.
             * 
             * @param value
             *     allowed object is
             *     {@link Byte }
             *     
             */
            public void setId(int value) {
                this.id = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="reasonnumber" type="{http://www.w3.org/2001/XMLSchema}byte"/>
         *         &lt;element name="reasontype" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="reasontypecode" type="{http://www.w3.org/2001/XMLSchema}byte"/>
         *         &lt;element name="reasondate" type="{http://www.w3.org/2001/XMLSchema}date"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "reasonnumber",
            "reasontype",
            "reasontypecode",
            "reasondate"
        })
        public static class Docreason {
        	@XmlElement(name = "НомерДокументу",required = true)
            protected String reasonnumber;
            @XmlElement(name = "ТипДокументу",required = true)
            protected String reasontype;
            @XmlElement(name = "КодТипуДокументу",required = true)
            protected String reasontypecode;
            @XmlElement(name = "ДатаДокументу",required = true)
            protected String reasondate;
            
            public Docreason(){
            	
            }
            
            public Docreason(String reasonnumber, String reasontype, String reasontypecode,
					String reasondate) {
				this.reasonnumber = reasonnumber;
				this.reasontype = reasontype;
				this.reasontypecode = reasontypecode;
				this.reasondate = reasondate;
			}

			/**
             * Gets the value of the reasonnumber property.
             * 
             */
            public String getReasonnumber() {
                return reasonnumber;
            }

            /**
             * Sets the value of the reasonnumber property.
             * 
             */
            public void setReasonnumber(String value) {
                this.reasonnumber = value;
            }

            /**
             * Gets the value of the reasontype property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getReasontype() {
                return reasontype;
            }

            /**
             * Sets the value of the reasontype property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setReasontype(String value) {
                this.reasontype = value;
            }

            /**
             * Gets the value of the reasontypecode property.
             * 
             */
            public String getReasontypecode() {
                return reasontypecode;
            }

            /**
             * Sets the value of the reasontypecode property.
             * 
             */
            public void setReasontypecode(String value) {
                this.reasontypecode = value;
            }

            /**
             * Gets the value of the reasondate property.
             * 
             * @return
             *     possible object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public String getReasondate() {
                return reasondate;
            }

            /**
             * Sets the value of the reasondate property.
             * 
             * @param value
             *     allowed object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public void setReasondate(String value) {
                this.reasondate = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="parameter" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;simpleContent>
     *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *                 &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}byte" />
     *                 &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
     *               &lt;/extension>
     *             &lt;/simpleContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlRootElement
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "parameter"
    })
    public static class Parameters {
    	@XmlElement(name="Параметр")
        protected List<COMDOC.Parameters.Parameter> parameter;

        /**
         * Gets the value of the parameter property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the parameter property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getParameter().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link COMDOC.Parameters.Parameter }
         * 
         * 
         */
        public List<COMDOC.Parameters.Parameter> getParameter() {
            if (parameter == null) {
                parameter = new ArrayList<COMDOC.Parameters.Parameter>();
            }
            return this.parameter;
        }
        public Parameters(){}
        
        public Parameters(List<Parameter> parameter) {
			this.parameter = parameter;
		}

		/**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;simpleContent>
         *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
         *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}byte" />
         *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
         *     &lt;/extension>
         *   &lt;/simpleContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "value"
        })
        public static class Parameter {

            @XmlValue
            protected String value;
            @XmlAttribute(name = "id")
            protected int id;
            @XmlAttribute(name = "name")
            protected String name;
            
            public Parameter(){}
            
            
            public Parameter(String value, int id, String name) {
				this.value = value;
				this.id = id;
				this.name = name;
			}

			/**
             * Gets the value of the value property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getValue() {
                return value;
            }

            /**
             * Sets the value of the value property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setValue(String value) {
                this.value = value;
            }

            /**
             * Gets the value of the id property.
             * 
             * @return
             *     possible object is
             *     {@link Byte }
             *     
             */
            public int getId() {
                return id;
            }

            /**
             * Sets the value of the id property.
             * 
             * @param value
             *     allowed object is
             *     {@link Byte }
             *     
             */
            public void setId(int value) {
                this.id = value;
            }

            /**
             * Gets the value of the name property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getName() {
                return name;
            }

            /**
             * Sets the value of the name property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setName(String value) {
                this.name = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="contractor" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="contractorstatus" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="contractorkind" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="contractorname" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="contractorcode" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *                   &lt;element name="ipn" type="{http://www.w3.org/2001/XMLSchema}long"/>
     *                   &lt;element name="certificatePDV" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
     *                   &lt;element name="GLN" type="{http://www.w3.org/2001/XMLSchema}long"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlRootElement
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "contractor"
    })
    public static class Sides {
    	@XmlElement(name="Контрагент",required=true)
        protected List<COMDOC.Sides.Contractor> contractor;
        /**
         * Gets the value of the contractor property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the contractor property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getContractor().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link COMDOC.Sides.Contractor }
         * 
         * 
         */
        public List<COMDOC.Sides.Contractor> getContractor() {
            if (contractor == null) {
                contractor = new ArrayList<COMDOC.Sides.Contractor>();
            }
            return this.contractor;
        }
        public Sides(){
        	
        }
        public Sides(List<Contractor> contractor) {
			this.contractor = contractor;
		}

		/**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "contractorstatus",
            "contractorkind",
            "contractorname",
            "contractorcode",
            "ipn",
            "certificatePDV",
            "gln"
        })
        public static class Contractor {
            @XmlElement(name="СтатусКонтрагента",required = true)
            protected String contractorstatus;
            @XmlElement(name="ВидОсоби",required = true)
            protected String contractorkind;
            @XmlElement(name="НазваКонтрагента",required = true)
            protected String contractorname;
            @XmlElement(name="КодКонтрагента",required = true)
            protected int contractorcode;
            @XmlElement(name="ІПН",required = true)
            protected long ipn;
            @XmlElement(name="СвідоцтвоПДВ",required = true)
            protected int certificatePDV;
            @XmlElement(name = "GLN",required = true)
            protected long gln;
            
            public Contractor(){
            	
            }
            public Contractor(String contractorstatus, String contractorkind, String contractorname, int contractorcode,
					long ipn, Integer certificatePDV, long gln) {
				this.contractorstatus = contractorstatus;
				this.contractorkind = contractorkind;
				this.contractorname = contractorname;
				this.contractorcode = contractorcode;
				this.ipn = ipn;
				this.certificatePDV = certificatePDV;
				this.gln = gln;
			}

			/**
             * Gets the value of the contractorstatus property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getContractorstatus() {
                return contractorstatus;
            }

            /**
             * Sets the value of the contractorstatus property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setContractorstatus(String value) {
                this.contractorstatus = value;
            }

            /**
             * Gets the value of the contractorkind property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getContractorkind() {
                return contractorkind;
            }

            /**
             * Sets the value of the contractorkind property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setContractorkind(String value) {
                this.contractorkind = value;
            }

            /**
             * Gets the value of the contractorname property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getContractorname() {
                return contractorname;
            }

            /**
             * Sets the value of the contractorname property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setContractorname(String value) {
                this.contractorname = value;
            }

            /**
             * Gets the value of the contractorcode property.
             * 
             */
            public int getContractorcode() {
                return contractorcode;
            }

            /**
             * Sets the value of the contractorcode property.
             * 
             */
            public void setContractorcode(int value) {
                this.contractorcode = value;
            }

            /**
             * Gets the value of the ipn property.
             * 
             */
            public long getIpn() {
                return ipn;
            }

            /**
             * Sets the value of the ipn property.
             * 
             */
            public void setIpn(long value) {
                this.ipn = value;
            }

            /**
             * Gets the value of the certificatePDV property.
             * 
             * @return
             *     possible object is
             *     {@link Integer }
             *     
             */
            public Integer getCertificatePDV() {
                return certificatePDV;
            }

            /**
             * Sets the value of the certificatePDV property.
             * 
             * @param value
             *     allowed object is
             *     {@link Integer }
             *     
             */
            public void setCertificatePDV(Integer value) {
                this.certificatePDV = value;
            }

            /**
             * Gets the value of the gln property.
             * 
             */
            public long getGLN() {
                return gln;
            }

            /**
             * Sets the value of the gln property.
             * 
             */
            public void setGLN(long value) {
                this.gln = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="row" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="posnum" type="{http://www.w3.org/2001/XMLSchema}byte"/>
     *                   &lt;element name="code">
     *                     &lt;complexType>
     *                       &lt;simpleContent>
     *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>long">
     *                           &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}byte" />
     *                         &lt;/extension>
     *                       &lt;/simpleContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                   &lt;element name="buyerarticle" type="{http://www.w3.org/2001/XMLSchema}byte"/>
     *                   &lt;element name="posname" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="itemcount" type="{http://www.w3.org/2001/XMLSchema}float"/>
     *                   &lt;element name="measurename" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="baseprice" type="{http://www.w3.org/2001/XMLSchema}float"/>
     *                   &lt;element name="PDV" type="{http://www.w3.org/2001/XMLSchema}float"/>
     *                   &lt;element name="price" type="{http://www.w3.org/2001/XMLSchema}float"/>
     *                   &lt;element name="totaltable">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="summwithPDV" type="{http://www.w3.org/2001/XMLSchema}float"/>
     *                             &lt;element name="summPDV" type="{http://www.w3.org/2001/XMLSchema}float"/>
     *                             &lt;element name="summ" type="{http://www.w3.org/2001/XMLSchema}float"/>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *                 &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}byte" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlRootElement
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "row"
    })
    public static class Table {
    	@XmlElement(name="Рядок")
        protected List<COMDOC.Table.Row> row;

        /**
         * Gets the value of the row property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the row property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getRow().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link COMDOC.Table.Row }
         * 
         * 
         */
        public List<COMDOC.Table.Row> getRow() {
            if (row == null) {
                row = new ArrayList<COMDOC.Table.Row>();
            }
            return this.row;
        }
        public Table(){
        	
        }
        public Table(List<Row> row) {
			this.row = row;
		}


		/**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "posnum",
            "code",
            "buyerarticle",
            "posname",
            "itemcount",
            "measurename",
            "baseprice",
            "pdv",
            "price",
            "totaltable"
        })
        public static class Row {
        	@XmlElement(name="НомПоз",required = true)
            protected int posnum;
        	@XmlElement(name="Штрихкод",required = true)
            protected COMDOC.Table.Row.Code code;
        	@XmlElement(name="АртикулПокупця",required = true)
            protected int buyerarticle;
            @XmlElement(name="Найменування",required = true)
            protected String posname;
            @XmlElement(name="ПрийнятаКількість",required = true)
            protected double itemcount;
            @XmlElement(name="ОдиницяВиміру",required = true)
            protected String measurename;
            @XmlElement(name="БазоваЦіна",required = true)
            protected double baseprice;
            @XmlElement(name="ПДВ",required = true)
            protected double pdv;
            @XmlElement(name="Ціна",required = true)
            protected double price;
            @XmlElement(name="ВсьогоПоРядку",required = true)
            protected COMDOC.Table.Row.Totaltable totaltable;
            @XmlAttribute(name = "id")
            protected int id;
            
            public Row(){
            	
            }
            public Row(int posnum, Code code, int buyerarticle, String posname, double itemcount, String measurename,
            		double baseprice, double pdv, double price, Totaltable totaltable, int id) {
				this.posnum = posnum;
				this.code = code;
				this.buyerarticle = buyerarticle;
				this.posname = posname;
				this.itemcount = itemcount;
				this.measurename = measurename;
				this.baseprice = baseprice;
				this.pdv = pdv;
				this.price = price;
				this.totaltable = totaltable;
				this.id = id;
			}
			/**
             * Gets the value of the posnum property.
             * 
             */
            public int getPosnum() {
                return posnum;
            }

            /**
             * Sets the value of the posnum property.
             * 
             */
            public void setPosnum(int value) {
                this.posnum = value;
            }

            /**
             * Gets the value of the code property.
             * 
             * @return
             *     possible object is
             *     {@link COMDOC.Table.Row.Code }
             *     
             */
            public COMDOC.Table.Row.Code getCode() {
                return code;
            }

            /**
             * Sets the value of the code property.
             * 
             * @param value
             *     allowed object is
             *     {@link COMDOC.Table.Row.Code }
             *     
             */
            public void setCode(COMDOC.Table.Row.Code value) {
                this.code = value;
            }

            /**
             * Gets the value of the buyerarticle property.
             * 
             */
            public int getBuyerarticle() {
                return buyerarticle;
            }

            /**
             * Sets the value of the buyerarticle property.
             * 
             */
            public void setBuyerarticle(int value) {
                this.buyerarticle = value;
            }

            /**
             * Gets the value of the posname property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getPosname() {
                return posname;
            }

            /**
             * Sets the value of the posname property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setPosname(String value) {
                this.posname = value;
            }

            /**
             * Gets the value of the itemcount property.
             * 
             */
            public double getItemcount() {
                return itemcount;
            }

            /**
             * Sets the value of the itemcount property.
             * 
             */
            public void setItemcount(double value) {
                this.itemcount = value;
            }

            /**
             * Gets the value of the measurename property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getMeasurename() {
                return measurename;
            }

            /**
             * Sets the value of the measurename property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setMeasurename(String value) {
                this.measurename = value;
            }

            /**
             * Gets the value of the baseprice property.
             * 
             */
            public double getBaseprice() {
                return baseprice;
            }

            /**
             * Sets the value of the baseprice property.
             * 
             */
            public void setBaseprice(double value) {
                this.baseprice = value;
            }

            /**
             * Gets the value of the pdv property.
             * 
             */
            public double getPDV() {
                return pdv;
            }

            /**
             * Sets the value of the pdv property.
             * 
             */
            public void setPDV(double value) {
                this.pdv = value;
            }

            /**
             * Gets the value of the price property.
             * 
             */
            public double getPrice() {
                return price;
            }

            /**
             * Sets the value of the price property.
             * 
             */
            public void setPrice(double value) {
                this.price = value;
            }

            /**
             * Gets the value of the totaltable property.
             * 
             * @return
             *     possible object is
             *     {@link COMDOC.Table.Row.Totaltable }
             *     
             */
            public COMDOC.Table.Row.Totaltable getTotaltable() {
                return totaltable;
            }

            /**
             * Sets the value of the totaltable property.
             * 
             * @param value
             *     allowed object is
             *     {@link COMDOC.Table.Row.Totaltable }
             *     
             */
            public void setTotaltable(COMDOC.Table.Row.Totaltable value) {
                this.totaltable = value;
            }

            /**
             * Gets the value of the id property.
             * 
             * @return
             *     possible object is
             *     {@link Byte }
             *     
             */
            public int getId() {
                return id;
            }

            /**
             * Sets the value of the id property.
             * 
             * @param value
             *     allowed object is
             *     {@link Byte }
             *     
             */
            public void setId(int value) {
                this.id = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;simpleContent>
             *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>long">
             *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}byte" />
             *     &lt;/extension>
             *   &lt;/simpleContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "value"
            })
            public static class Code {

                @XmlValue
                protected String value;
                @XmlAttribute(name = "id")
                protected int id;
                
                public Code(){
                	
                }
                
                public Code(String value, int id) {
					this.value = value;
					this.id = id;
				}

				/**
                 * Gets the value of the value property.
                 * 
                 */
                public String getValue() {
                    return value;
                }

                /**
                 * Sets the value of the value property.
                 * 
                 */
                public void setValue(String value) {
                    this.value = value;
                }

                /**
                 * Gets the value of the id property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link Byte }
                 *     
                 */
                public int getId() {
                    return id;
                }

                /**
                 * Sets the value of the id property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link Byte }
                 *     
                 */
                public void setId(int value) {
                    this.id = value;
                }

            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="summwithPDV" type="{http://www.w3.org/2001/XMLSchema}float"/>
             *         &lt;element name="summPDV" type="{http://www.w3.org/2001/XMLSchema}float"/>
             *         &lt;element name="summ" type="{http://www.w3.org/2001/XMLSchema}float"/>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "summwithPDV",
                "summPDV",
                "summ"
            })
            public static class Totaltable {
            	@XmlElement(name="СумаБезПДВ",required = true)
                protected double summwithPDV;
            	@XmlElement(name="СумаПДВ",required = true)
                protected double summPDV;
            	@XmlElement(name="Сума",required = true)
                protected double summ;
                
                public Totaltable(){}

                public Totaltable(double summwithPDV, double summPDV, double summ) {
					this.summwithPDV = summwithPDV;
					this.summPDV = summPDV;
					this.summ = summ;
				}

				/**
                 * Gets the value of the summwithPDV property.
                 * 
                 */
                public double getSummwithPDV() {
                    return summwithPDV;
                }

                /**
                 * Sets the value of the summwithPDV property.
                 * 
                 */
                public void setSummwithPDV(double value) {
                    this.summwithPDV = value;
                }

                /**
                 * Gets the value of the summPDV property.
                 * 
                 */
                public double getSummPDV() {
                    return summPDV;
                }

                /**
                 * Sets the value of the summPDV property.
                 * 
                 */
                public void setSummPDV(double value) {
                    this.summPDV = value;
                }

                /**
                 * Gets the value of the summ property.
                 * 
                 */
                public double getSumm() {
                    return summ;
                }

                /**
                 * Sets the value of the summ property.
                 * 
                 */
                public void setSumm(double value) {
                    this.summ = value;
                }

            }

        }

    }

}
