//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.07.06 at 05:37:09 PM EEST 
//


package com.rosteach.xml;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="NUMBER" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="DATE" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="DELIVERYDATE" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="ORDERNUMBER" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="ORDERDATE" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="DELIVERYNOTENUMBER" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="DELIVERYNOTEDATE" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="CAMPAIGNNUMBER" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="HEAD">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="SUPPLIER" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="BUYER" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="DELIVERYPLACE" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="SENDER" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="RECIPIENT" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="EDIINTERCHANGEID" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="PACKINGSEQUENCE">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="POSITION" maxOccurs="unbounded">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="POSITIONNUMBER" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                                       &lt;element name="PRODUCT" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                                       &lt;element name="PRODUCTIDBUYER" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                                       &lt;element name="DELIVEREDQUANTITY" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                                       &lt;element name="DELIVEREDUNIT" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="ORDEREDQUANTITY" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                                       &lt;element name="ORDERUNIT" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="PRICE" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *                                       &lt;element name="DESCRIPTION" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "number",
    "date",
    "deliverydate",
    "ordernumber",
    "orderdate",
    "deliverynotenumber",
    "deliverynotedate",
    "campaignnumber",
    "head"
})
@XmlRootElement(name = "DESADV")
public class DESADV {

    @XmlElement(name = "NUMBER")
    protected int number;
    @XmlElement(name = "DATE", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar date;
    @XmlElement(name = "DELIVERYDATE", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar deliverydate;
    @XmlElement(name = "ORDERNUMBER")
    protected int ordernumber;
    @XmlElement(name = "ORDERDATE", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar orderdate;
    @XmlElement(name = "DELIVERYNOTENUMBER")
    protected String deliverynotenumber;
    @XmlElement(name = "DELIVERYNOTEDATE", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar deliverynotedate;
    @XmlElement(name = "CAMPAIGNNUMBER")
    protected int campaignnumber;
    @XmlElement(name = "HEAD", required = true)
    protected DESADV.HEAD head;

    /**
     * Gets the value of the number property.
     * 
     */
    public int getNUMBER() {
        return number;
    }

    /**
     * Sets the value of the number property.
     * 
     */
    public void setNUMBER(int value) {
        this.number = value;
    }

    /**
     * Gets the value of the date property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDATE() {
        return date;
    }

    /**
     * Sets the value of the date property.
     * 
     * @param date2
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDATE(XMLGregorianCalendar date2) {
        this.date = date2;
    }

    /**
     * Gets the value of the deliverydate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDELIVERYDATE() {
        return deliverydate;
    }

    /**
     * Sets the value of the deliverydate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDELIVERYDATE(XMLGregorianCalendar value) {
        this.deliverydate = value;
    }

    /**
     * Gets the value of the ordernumber property.
     * 
     */
    public int getORDERNUMBER() {
        return ordernumber;
    }

    /**
     * Sets the value of the ordernumber property.
     * 
     */
    public void setORDERNUMBER(int value) {
        this.ordernumber = value;
    }

    /**
     * Gets the value of the orderdate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getORDERDATE() {
        return orderdate;
    }

    /**
     * Sets the value of the orderdate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setORDERDATE(XMLGregorianCalendar value) {
        this.orderdate = value;
    }

    /**
     * Gets the value of the deliverynotenumber property.
     * 
     */
    public String getDELIVERYNOTENUMBER() {
        return deliverynotenumber;
    }

    /**
     * Sets the value of the deliverynotenumber property.
     * 
     */
    public void setDELIVERYNOTENUMBER(String value) {
        this.deliverynotenumber = value;
    }

    /**
     * Gets the value of the deliverynotedate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDELIVERYNOTEDATE() {
        return deliverynotedate;
    }

    /**
     * Sets the value of the deliverynotedate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDELIVERYNOTEDATE(XMLGregorianCalendar value) {
        this.deliverynotedate = value;
    }

    /**
     * Gets the value of the campaignnumber property.
     * 
     */
    public int getCAMPAIGNNUMBER() {
        return campaignnumber;
    }

    /**
     * Sets the value of the campaignnumber property.
     * 
     */
    public void setCAMPAIGNNUMBER(int value) {
        this.campaignnumber = value;
    }

    /**
     * Gets the value of the head property.
     * 
     * @return
     *     possible object is
     *     {@link DESADV.HEAD }
     *     
     */
    public DESADV.HEAD getHEAD() {
        return head;
    }

    /**
     * Sets the value of the head property.
     * 
     * @param value
     *     allowed object is
     *     {@link DESADV.HEAD }
     *     
     */
    public void setHEAD(DESADV.HEAD value) {
        this.head = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="SUPPLIER" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="BUYER" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="DELIVERYPLACE" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="SENDER" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="RECIPIENT" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="EDIINTERCHANGEID" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="PACKINGSEQUENCE">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="POSITION" maxOccurs="unbounded">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="POSITIONNUMBER" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *                             &lt;element name="PRODUCT" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *                             &lt;element name="PRODUCTIDBUYER" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *                             &lt;element name="DELIVEREDQUANTITY" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *                             &lt;element name="DELIVEREDUNIT" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="ORDEREDQUANTITY" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *                             &lt;element name="ORDERUNIT" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="PRICE" type="{http://www.w3.org/2001/XMLSchema}double"/>
     *                             &lt;element name="DESCRIPTION" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "supplier",
        "buyer",
        "deliveryplace",
        "sender",
        "recipient",
        "ediinterchangeid",
        "packingsequence"
    })
    public static class HEAD {

        @XmlElement(name = "SUPPLIER")
        protected String supplier;
        @XmlElement(name = "BUYER")
        protected int buyer;
        @XmlElement(name = "DELIVERYPLACE")
        protected int deliveryplace;
        @XmlElement(name = "SENDER")
        protected String sender;
        @XmlElement(name = "RECIPIENT")
        protected int recipient;
        @XmlElement(name = "EDIINTERCHANGEID")
        protected int ediinterchangeid;
        @XmlElement(name = "PACKINGSEQUENCE", required = true)
        protected DESADV.HEAD.PACKINGSEQUENCE packingsequence;

        /**
         * Gets the value of the supplier property.
         * 
         */
        public String getSUPPLIER() {
            return supplier;
        }

        /**
         * Sets the value of the supplier property.
         * 
         */
        public void setSUPPLIER(String value) {
            this.supplier = value;
        }

        /**
         * Gets the value of the buyer property.
         * 
         */
        public int getBUYER() {
            return buyer;
        }

        /**
         * Sets the value of the buyer property.
         * 
         */
        public void setBUYER(int value) {
            this.buyer = value;
        }

        /**
         * Gets the value of the deliveryplace property.
         * 
         */
        public int getDELIVERYPLACE() {
            return deliveryplace;
        }

        /**
         * Sets the value of the deliveryplace property.
         * 
         */
        public void setDELIVERYPLACE(int value) {
            this.deliveryplace = value;
        }

        /**
         * Gets the value of the sender property.
         * 
         */
        public String getSENDER() {
            return sender;
        }

        /**
         * Sets the value of the sender property.
         * 
         */
        public void setSENDER(String value) {
            this.sender = value;
        }

        /**
         * Gets the value of the recipient property.
         * 
         */
        public int getRECIPIENT() {
            return recipient;
        }

        /**
         * Sets the value of the recipient property.
         * 
         */
        public void setRECIPIENT(int value) {
            this.recipient = value;
        }

        /**
         * Gets the value of the ediinterchangeid property.
         * 
         */
        public int getEDIINTERCHANGEID() {
            return ediinterchangeid;
        }

        /**
         * Sets the value of the ediinterchangeid property.
         * 
         */
        public void setEDIINTERCHANGEID(int value) {
            this.ediinterchangeid = value;
        }

        /**
         * Gets the value of the packingsequence property.
         * 
         * @return
         *     possible object is
         *     {@link DESADV.HEAD.PACKINGSEQUENCE }
         *     
         */
        public DESADV.HEAD.PACKINGSEQUENCE getPACKINGSEQUENCE() {
            return packingsequence;
        }

        /**
         * Sets the value of the packingsequence property.
         * 
         * @param value
         *     allowed object is
         *     {@link DESADV.HEAD.PACKINGSEQUENCE }
         *     
         */
        public void setPACKINGSEQUENCE(DESADV.HEAD.PACKINGSEQUENCE value) {
            this.packingsequence = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="POSITION" maxOccurs="unbounded">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="POSITIONNUMBER" type="{http://www.w3.org/2001/XMLSchema}int"/>
         *                   &lt;element name="PRODUCT" type="{http://www.w3.org/2001/XMLSchema}int"/>
         *                   &lt;element name="PRODUCTIDBUYER" type="{http://www.w3.org/2001/XMLSchema}int"/>
         *                   &lt;element name="DELIVEREDQUANTITY" type="{http://www.w3.org/2001/XMLSchema}int"/>
         *                   &lt;element name="DELIVEREDUNIT" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="ORDEREDQUANTITY" type="{http://www.w3.org/2001/XMLSchema}int"/>
         *                   &lt;element name="ORDERUNIT" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="PRICE" type="{http://www.w3.org/2001/XMLSchema}double"/>
         *                   &lt;element name="DESCRIPTION" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "position"
        })
        public static class PACKINGSEQUENCE {

            @XmlElement(name = "POSITION", required = true)
            protected List<DESADV.HEAD.PACKINGSEQUENCE.POSITION> position;

            /**
             * Gets the value of the position property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the position property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getPOSITION().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link DESADV.HEAD.PACKINGSEQUENCE.POSITION }
             * 
             * 
             */
            public List<DESADV.HEAD.PACKINGSEQUENCE.POSITION> getPOSITION() {
                if (position == null) {
                    position = new ArrayList<DESADV.HEAD.PACKINGSEQUENCE.POSITION>();
                }
                return this.position;
            }
            public boolean addPOSITION(POSITION position) {
                if (position == null) {
                    return false;
                }
                else{
                	List<DESADV.HEAD.PACKINGSEQUENCE.POSITION> list= new ArrayList<DESADV.HEAD.PACKINGSEQUENCE.POSITION>();
                	list.add(position);
                	return true;
                }
            }
            public void setPOSITION(List<DESADV.HEAD.PACKINGSEQUENCE.POSITION> positions){
            	this.position = positions;
            }
            
            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="POSITIONNUMBER" type="{http://www.w3.org/2001/XMLSchema}int"/>
             *         &lt;element name="PRODUCT" type="{http://www.w3.org/2001/XMLSchema}int"/>
             *         &lt;element name="PRODUCTIDBUYER" type="{http://www.w3.org/2001/XMLSchema}int"/>
             *         &lt;element name="DELIVEREDQUANTITY" type="{http://www.w3.org/2001/XMLSchema}int"/>
             *         &lt;element name="DELIVEREDUNIT" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="ORDEREDQUANTITY" type="{http://www.w3.org/2001/XMLSchema}int"/>
             *         &lt;element name="ORDERUNIT" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="PRICE" type="{http://www.w3.org/2001/XMLSchema}double"/>
             *         &lt;element name="DESCRIPTION" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "positionnumber",
                "product",
                "productidbuyer",
                "deliveredquantity",
                "deliveredunit",
                "orderedquantity",
                "orderunit",
                "price",
                "description"
            })
            public static class POSITION {

                @XmlElement(name = "POSITIONNUMBER")
                protected int positionnumber;
                @XmlElement(name = "PRODUCT")
                protected String product;
                @XmlElement(name = "PRODUCTIDBUYER")
                protected int productidbuyer;
                @XmlElement(name = "DELIVEREDQUANTITY")
                protected Double deliveredquantity;
                @XmlElement(name = "DELIVEREDUNIT", required = true)
                protected String deliveredunit;
                @XmlElement(name = "ORDEREDQUANTITY")
                protected int orderedquantity;
                @XmlElement(name = "ORDERUNIT", required = true)
                protected String orderunit;
                @XmlElement(name = "PRICE")
                protected double price;
                @XmlElement(name = "DESCRIPTION", required = true)
                protected String description;

                /**
                 * Gets the value of the positionnumber property.
                 * 
                 */
                public int getPOSITIONNUMBER() {
                    return positionnumber;
                }

                /**
                 * Sets the value of the positionnumber property.
                 * 
                 */
                public void setPOSITIONNUMBER(int value) {
                    this.positionnumber = value;
                }

                /**
                 * Gets the value of the product property.
                 * 
                 */
                public String getPRODUCT() {
                    return product;
                }

                /**
                 * Sets the value of the product property.
                 * 
                 */
                public void setPRODUCT(String value) {
                    this.product = value;
                }

                /**
                 * Gets the value of the productidbuyer property.
                 * 
                 */
                public int getPRODUCTIDBUYER() {
                    return productidbuyer;
                }

                /**
                 * Sets the value of the productidbuyer property.
                 * 
                 */
                public void setPRODUCTIDBUYER(int value) {
                    this.productidbuyer = value;
                }

                /**
                 * Gets the value of the deliveredquantity property.
                 * 
                 */
                public Double getDELIVEREDQUANTITY() {
                    return deliveredquantity;
                }

                /**
                 * Sets the value of the deliveredquantity property.
                 * 
                 */
                public void setDELIVEREDQUANTITY(Double value) {
                    this.deliveredquantity = value;
                }

                /**
                 * Gets the value of the deliveredunit property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getDELIVEREDUNIT() {
                    return deliveredunit;
                }

                /**
                 * Sets the value of the deliveredunit property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setDELIVEREDUNIT(String value) {
                    this.deliveredunit = value;
                }

                /**
                 * Gets the value of the orderedquantity property.
                 * 
                 */
                public int getORDEREDQUANTITY() {
                    return orderedquantity;
                }

                /**
                 * Sets the value of the orderedquantity property.
                 * 
                 */
                public void setORDEREDQUANTITY(int value) {
                    this.orderedquantity = value;
                }

                /**
                 * Gets the value of the orderunit property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getORDERUNIT() {
                    return orderunit;
                }

                /**
                 * Sets the value of the orderunit property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setORDERUNIT(String value) {
                    this.orderunit = value;
                }

                /**
                 * Gets the value of the price property.
                 * 
                 */
                public double getPRICE() {
                    return price;
                }

                /**
                 * Sets the value of the price property.
                 * 
                 */
                public void setPRICE(double value) {
                    this.price = value;
                }

                /**
                 * Gets the value of the description property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getDESCRIPTION() {
                    return description;
                }

                /**
                 * Sets the value of the description property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setDESCRIPTION(String value) {
                    this.description = value;
                }

            }

        }

    }

}
